### ISSUE TITLE
Automatically run the MazeRunner

### ISSUE THREAD

**Issue by EC2EZ4RD** [crowdAI/marLo#22]
Very nice seeing marLo getting ready.
I installed Malmo manually about 2 months ago, and could run all the python examples.
Today I installed marLo by `pip3 install marlo` on Windows. Then I ran launchClient.bat on port 10000, but once I ran `import marlo`, the Minecraft automatically began the MazeRunner. Even I wrote the whole script and change to other environments, it still kept on mazerunner.

**Comment by spMohanty** [comment]
@EC2EZ4RD : This was reported by @idvhfd too ! I will have a look at it in a bit and get back to you.

**Comment by EC2EZ4RD** [comment]
Thank you very much!

**Comment by EC2EZ4RD** [comment]
Hi, it seems that this problem is still existing after I reinstall marLo. How about the situation :) ?

**Comment by spMohanty** [comment]
@EC2EZ4RD : We are not able to reproduce the issue at the moment. 
But we are releasing conda packages for window too in a day or so, and hopefully that should solve this issue.

**Comment by EC2EZ4RD** [comment]
I have reinstall malmo and this issue was resolved. Maybe this issue can be closed

**Comment by spMohanty** [comment]
@EC2EZ4RD : Great ! I am closing this issue then !
