### ISSUE TITLE
what does the obs that is returned from step() function mean? 

### ISSUE THREAD

**Issue by ProQianXiao** [crowdAI/marLo#41]
I am trying the Single Agent Example from [https://marlo.readthedocs.io/en/latest/usage/singleagent_example.html](url), I run the example and I print the obs that is returned from step function like this.
`while not done:
  _action = env.action_space.sample()
  obs, reward, done, info = env.step(_action)
 print(obs)`
Then I get the output of obs, it looks like ndarray,

![3](https://user-images.githubusercontent.com/25978988/44662963-c3d65580-aa41-11e8-8dd4-39aa9c97216e.png)

But what does that mean? The pixel point information of next state? Or others?  Could you help me to settle that?

**Comment by spMohanty** [comment]
@ProQianXiao : This refers to the RGB frame representing what you would see on the screen of the game if you were playing the game yourself. 
Does this answer your question ?

**Comment by ProQianXiao** [comment]
@spMohanty Thank you for your reply. Can I understand this? The obs that is returned from step function represents the state information, and I could use it as a parameter to pass to my algorithm. Is it right?

In addition, I also want to know how can we get the detailed information about the findThegoal environment, such as description, actions available, rewards, discrete action or continuous action?
I search the envs, but there is no findThegoal environment.
![qq 20180828094747](https://user-images.githubusercontent.com/25978988/44695974-2f530e00-aaa8-11e8-93ab-4c6ff8035c39.png)
Looking forward to your reply.

**Comment by douglasrizzo** [comment]
`obs` is an image, a screen capture of the game. Each of the three values in the lines from your terminal represent the R, G and B values of a pixel from the screen. If you do something like:

    obs, reward, done, info = env.step(_action)    
    im = PIL.Image.fromarray(obs)
    im.save('image.png')

you'll see that a screen capture of the game will be saved as a PNG file. I hope that helps.

**Comment by ProQianXiao** [comment]
@douglasrizzo Thanks very much, that helps me a lot.

**Comment by douglasrizzo** [comment]
@ProQianXiao The _FindTheGoal_ environment is named _Basic_ in the screenshot you provided. However, I don't think you'll find any relevant info in the repository. You just have to interface with the game through the marlo package, send actions and receive rewards and new observations.
I suggest you take a look at the [usage examples](https://marlo.readthedocs.io/en/latest/usage.html). Personally, I don't think you'll have much structured data to work with (_e.g._ a discretized grid world). You'll just have to work with the image inputs.

**Comment by spMohanty** [comment]
Thanks @douglasrizzo for the clarification.
And thats correct, in this competition, we are focussing on just image frames as observation.

At a later point in time, we do have plans to make the grid word available as observation (and make it configurable), but that will anyway not be allowed in this competition.

**Comment by ProQianXiao** [comment]
@douglasrizzo @spMohanty  that is very kind of you. I figure out what the obs means and the how to use state information now. Thanks very much again.
