### ISSUE TITLE
Implement Soft Reset

### ISSUE THREAD

**Issue by justinglibert** [crowdAI/marLo#57]
According to this Malmo issue [here](https://github.com/Microsoft/malmo/issues/720) you can implement soft reset in the mission.xml to make the training process faster (most of the time is taken by the reloading between two missions). I'm ok with implementing this but first I would like to know from @spMohanty and the other maintainers how best it would fit in the framework

**Comment by spMohanty** [comment]
@justinglibert : Thats a really good idea ! Given its an addition to the mission.xml, it can be easily added as an extra param in the game params, and then rendered conditionally using the jinja2 templating system we use to render the final mission.xmls. And then use the soft-reset conditionally during the env.resets

Please feel free to send in a pull request ! This would definitely help a lot of participants !

**Comment by justinglibert** [comment]
Just realised it's actually built into Marlo. Just set force_reset to false in the parameters dictionary when you init the environment.
